grace:
  mutable: True
  default: 7
  lcap: 3
  hcap: 30
max_players:
  mutable: True
  default: 9
  hcap: 10
min_players:
  mutable: False
  default: 3
  lcap: 2
lives:
  mutable: True
  default: 2
  lcap: 1
